kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nfs-client-provisioner-for-mysql
subjects:
  - kind: ServiceAccount
    name: nfs-client-provisioner-for-mysql
    namespace: default
roleRef:
  kind: ClusterRole
  name: nfs-client-provisioner-for-mysql
  apiGroup: rbac.authorization.k8s.io

