kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: stor-for-mysql-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage-for-mysql"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
